Pi4 branch
srsran/srsRAN_4G_docs pull request #2
Opened 2020-05-12 13:13 UTC by kbarlee

Adding a subpage to app notes, providing a stable Pi4 setup guide and config

2020-05-12 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/srsLTE/srsLTE_docs?pullRequest=2) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/srsLTE/srsLTE_docs?pullRequest=2) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/srsLTE/srsLTE_docs?pullRequest=2) it.</sub>

2020-05-12 19:18 UTC, andrepuschmann requested changes
Thanks a lot for tutorial. A few minor things to update but most importantly we need to check why 19.12 works better for you and 20.04.1 doesn't. This shouldn't be the case ;-)

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/README
> +The docs of the norf application note require sphinx, and the sphinx-seqdiag and sphinx-blockdiag extensions.
pi4 application note

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +The setup instructions provided below have been tested with a **Raspberry Pi 4B /4GB rev 1.2** running the Ubuntu Server 20.04 LTS x64 Arm image. It has not been tested with the rev 1.1 board, boards
arm64 or better `aarch64` image

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +Due to the power requirements of the SDRs, you must use an external power source. This can be acheived with a 'Y' cable, such as this:
achieved

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo add-apt-repository ppa:ettusresearch/uhd
Is the PPA really required? I think they don't even have images for Ubuntu 20.04 and the UHD 3.15 is part of the default packages.

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo ldconfig
why exactly this hash? Doesn't work with the last release tag for example?

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo add-apt-repository -y ppa:myriadrf/drivers
why is the PPA needed if we install from source?

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout d045213fb9cbf98c83c06d7c17197a9dcbfddacf
I'd rather use the release tag and even make this optional because just checking out the latest master should work

2020-05-12 19:18 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +* Stability issues were noted on the Pi with the most recent release of srsLTE (v20.04), hence srsLTE version 19.12 is being used.
mmh, this is not good, we need to investigate this. Have you tried with 20.04.1?

2020-05-12 21:22 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo add-apt-repository ppa:ettusresearch/uhd
Potentially not - this is just part of my past setup for UHD. Will remove for now.

2020-05-12 21:23 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo ldconfig
will check this

2020-05-12 21:24 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo add-apt-repository -y ppa:myriadrf/drivers
again, good point!

2020-05-13 00:15 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  sudo ldconfig
Does not work with master, does work with release v20.01.0. Have updated this to use the release tag.

2020-05-13 00:15 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout d045213fb9cbf98c83c06d7c17197a9dcbfddacf
Have updated this to use the tag release_19_12.

2020-05-13 23:26 UTC, kbarlee commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +* Stability issues were noted on the Pi with the most recent release of srsLTE (v20.04), hence srsLTE version 19.12 is being used.
Have now tested again with 19.12, 20.04 and 20.04.1. Only 19.12 seems to work. 

There is chatter with the other two, but devices are unable to connect. I will send you enb logs. 
```
Disconnecting rnti=0x5c.
RACH:  tti=2111, preamble=45, offset=1, temp_crnti=0x5d
Disconnecting rnti=0x5d.
RACH:  tti=2201, preamble=5, offset=1, temp_crnti=0x5e
Disconnecting rnti=0x5e.
RACH:  tti=2291, preamble=40, offset=1, temp_crnti=0x5f
Disconnecting rnti=0x5f.
RACH:  tti=2381, preamble=40, offset=1, temp_crnti=0x60
Disconnecting rnti=0x60.
RACH:  tti=2471, preamble=10, offset=1, temp_crnti=0x61
Disconnecting rnti=0x61.
RACH:  tti=2561, preamble=15, offset=1, temp_crnti=0x62
```

2020-05-15 07:52 UTC, andrepuschmann reviewed
Just wanted to reinforce the goal for publishing this app note as soon as we have found/solved the issue you are seeing with the newer releases.

2020-05-15 07:52 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/conf.py
> +project = u'norf application note'
Can you ctrl+f through the pull-request and replace all _norf_ with _pi4_?

2020-05-15 07:52 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout tags/soapy-sdr-0.7.2
I am aware that the 19.12 release does not compile with the recent Soapy version. But once we have the new release working I think this restriction can also go. Let's see.

2020-05-15 07:52 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout tags/release_19_12
Let's aim to remove that restriction ... I'll follow up with you on that ..

2020-05-19 19:35 UTC, andrepuschmann approved these changes
Thanks for your effort on this again. We could reproduce the issue you were having with 20.04 but decided to not fix it straight away in the public release. Therefore, I'd like to ask you to adapt the last bullet point a bit to provide a better explanation to the user. Also, can you please rebase the branch. It seems with the merge of the last appnote there is now a tiny conflict.

2020-05-19 19:35 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout tags/soapy-sdr-0.7.2
We leave this until we've fixed the attach issue in the new release.

2020-05-19 19:35 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +  git checkout tags/release_19_12
Same, we leave it like this checking out 19.12 until we've solved the attach issue publicly

2020-05-19 19:35 UTC, andrepuschmann commented on srslte_user_manuals/source/app_notes/source/pi4/source/index.rst
> +* Stability issues were noted on the Pi with the most recent release of srsLTE (v20.04), hence srsLTE version 19.12 is being used.
We've investigated the situation with 20.04 and it turns out that we have made a change in the PRACH handling that turns out to worsen things for weaker devices such as the Pi4. We are planning to actively support the Pi4 in the future and will include the device in our CI/CD for the next release. But since this is not the case for 20.04 we are not hot-fixing the issue right now.
@kbarlee could you perhaps just change this line under _known issues_ as write something like: _"For bandwidths above 6 PRB it is recommended to use srsLTE 19.12 instead of the most recent release 20.04. We have identified an issue in the PRACH handling mainly affecting low-power devices that will be fixed in the upcoming release."_

2020-05-20 11:05 UTC, kbarlee commented
Hey Andre - I think that's everything updated now, with cv2x conflict dealt with too.

2020-05-20 11:57 UTC, merged

2020-05-20 11:58 UTC, andrepuschmann commented
Once again, thanks a ton for this contribution.